name: Docker pipeline

on:
  push:
    branches:
      - main

jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:

      - name: checking out the latest code
        uses: actions/checkout@v7
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Image 🐳
        id: image
        uses: deploy-actions/push-to-ecr@v1
        with:
          repository-name: mohammad-docker
          image-tag: ${{ github.sha }}

  deployjob:
    needs: buildjob
    runs-on: ubuntu-latest
    steps:
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: whoami
